publish a version on npm every time something is merged on master
buildo/eslint-config pull request #117
Opened 2017-06-05 16:48 UTC by giogonzo

2017-06-05 16:51 UTC, gabro reviewed
Doesn't this hang forever waiting for user input without a .smoothreleaserc?

2017-06-05 16:51 UTC, gabro commented on .drone.yml
> +      - npm install
You can use yarn (or maybe node:8?)

2017-06-05 16:52 UTC, giogonzo commented
@gabro yes, I'll add one

2017-06-07 14:15 UTC, giogonzo commented
@FrancescoCioria will this `.smooth-releaserc` be enough?

2017-06-07 14:38 UTC, FrancescoCioria requested changes
`smooth-release` will also try to push some changes to origin.
I remember we had to add a couple of steps to enable the CI to push
@gabro am I right? can you help with that?

2017-06-07 16:23 UTC, FrancescoCioria approved these changes

2017-06-08 10:00 UTC, gabro approved these changes

2017-06-08 10:00 UTC, merged